implemented JdbcPhoneDao JdbcPhoneDaoTest and ProductListPageControll…
ElPerro3228/phoneshop pull request #1
Opened 2020-05-22 16:10 UTC by ElPerro3228

2020-05-22 17:42 UTC, AndreikaInactive requested changes

2020-05-22 17:42 UTC, AndreikaInactive commented on core/src/main/java/com/es/core/model/phone/JdbcPhoneDao.java
> +    private static final String UPDATE_QUERY = "update phones set " +
Как нибудь типа update phone by id будет выразительней

2020-05-22 17:42 UTC, AndreikaInactive commented on core/src/main/java/com/es/core/model/phone/JdbcPhoneDao.java
> +            return phone;
Отличный трюк)) давай все же по человечески - обработать именно отсутствие результата у квери

2020-05-22 17:42 UTC, AndreikaInactive commented on core/src/main/java/com/es/core/model/phone/JdbcPhoneDao.java
> +        NamedParameterJdbcTemplate namedParameterJdbcTemplate = new NamedParameterJdbcTemplate(jdbcTemplate.getDataSource());
Хорошо что named, плохо что не инжектится сппингом

2020-05-22 17:42 UTC, AndreikaInactive commented on core/src/main/java/com/es/core/model/phone/JdbcPhoneDao.java
> +        NamedParameterJdbcTemplate namedParameterJdbcTemplate = new NamedParameterJdbcTemplate(jdbcTemplate.getDataSource());
И тут new

2020-05-22 17:42 UTC, AndreikaInactive commented on core/src/main/java/com/es/core/model/phone/JdbcPhoneDao.java
> +        return jdbcTemplate.query("select * from phones offset " + offset + " limit " + limit, new PhoneRowMapper(Phone.class));
Маппер сделай бином

2020-05-22 17:42 UTC, AndreikaInactive commented on core/src/main/resources/conf/application.properties
> +db.insertSchema=true/false
Так true или false?)

2020-05-22 17:42 UTC, AndreikaInactive commented on core/src/test/java/com/es/core/model/phone/JdbcPhoneDaoTest.java
> +        assertEquals("", phone.getBrand());
Те же комменты по тестам как и брату

2020-05-22 17:42 UTC, AndreikaInactive commented on core/src/test/resources/context/applicationContext-core-test
> +    <jdbc:initialize-database enabled="true" data-source="dataSource">
Можно даже запихнуть в коре и брать флаги из пропертей, в тестах только юзать другой проперти файл

2020-05-22 17:42 UTC, AndreikaInactive commented on web/src/test/java/com/es/phoneshop/web/controller/pages/ProductListPageControllerTest.java
> +        MockMvc mockMvc = standaloneSetup(controller).setSingleView(
Почему 10? И зачем ставить jsp во вью в юнит тесте?

2020-05-22 19:08 UTC, ElPerro3228 commented on web/src/test/java/com/es/phoneshop/web/controller/pages/ProductListPageControllerTest.java
> +        MockMvc mockMvc = standaloneSetup(controller).setSingleView(
у меня без setsingleview тест не работал, а 10 это потому что в контроллере первые 10 телефонов выводятся.

2020-05-22 19:20 UTC, ElPerro3228 commented on core/src/main/java/com/es/core/model/phone/JdbcPhoneDao.java
> +            return phone;
я просто не очень понимаю, как обработать отсутствие результата, поэтому и оставил это в блоке try. Я думал бросать исключение если результата не было, но с другой стороны метод возвращает optional и отсутствие результата можно проверить  методом ispresent.

2020-05-25 09:03 UTC, AndreikaInactive requested changes

2020-05-25 09:03 UTC, AndreikaInactive commented on core/src/test/java/com/es/core/model/phone/AbstractTest.java
> +@PropertySource("classpath:conf/application.properties")
обычно включаются в контексте, а здесь разве что добавить тестовые проперти, для оверрайда

2020-05-25 09:03 UTC, AndreikaInactive commented on core/src/test/java/com/es/core/model/phone/AbstractTest.java
> +        jdbcTemplate.execute(IOUtils.resourceToString(testScript, StandardCharsets.UTF_8));
а если база разрастётся? выполнять это для каждого теста?
почитай про аннотацию Transactional и её применение в тестах

2020-05-25 09:03 UTC, AndreikaInactive commented on core/src/main/java/com/es/core/model/phone/JdbcPhoneDao.java
> +            return phone;
насколько помню, jdbcTemplate кинет эксепшен, если не найдёт - его можно словить
да, смысл Optional в том что null или exception из метода обычно не приходят

2020-05-25 09:03 UTC, AndreikaInactive commented on core/src/main/java/com/es/core/model/phone/JdbcPhoneDao.java
> +    private static final String UPDATE_QUERY_BY_ID = "update phones set " +
UPDATE_PHONE_BY_ID

2020-05-25 09:03 UTC, AndreikaInactive commented on core/src/main/java/com/es/core/model/phone/PhoneRowMapper.java
> +                "join colors on colorId = colors.id where phoneId = " + phone.getId() + ";", new BeanPropertyRowMapper(Color.class));
тоже можно сделать бином

2020-05-26 09:24 UTC, AndreikaInactive requested changes

2020-05-26 09:24 UTC, AndreikaInactive commented on core/src/main/java/com/es/core/model/phone/PhoneDao.java
> +@Transactional
зачем на интерфейс?

2020-05-26 09:24 UTC, AndreikaInactive commented on core/src/test/java/com/es/core/model/phone/AbstractTest.java
> +public abstract class AbstractTest {
AbstractIntegrationTest - так понятней в чем его смысл

2020-05-26 09:24 UTC, AndreikaInactive commented
резолвай плз пофикшеные дискуссии

2020-05-26 16:03 UTC, merged