Task 2
ElPerro3228/phoneshop pull request #2
Opened 2020-05-30 17:52 UTC by ElPerro3228

2020-06-09 13:42 UTC, AndreikaInactive requested changes

2020-06-09 13:42 UTC, AndreikaInactive commented on core/src/main/java/com/es/core/model/phone/JdbcPhoneDao.java
> +                                       SqlParameterSource sqlParameterSource) {
странный параметр для публичного метода

2020-06-09 13:42 UTC, AndreikaInactive commented on core/src/main/java/com/es/core/cart/HttpSessionCartService.java
>          for (Long phoneId : items.keySet()) {
entrySet можно сразу

2020-06-09 13:42 UTC, AndreikaInactive commented on core/src/main/java/com/es/core/cart/HttpSessionCartService.java
> +        cart.setCartPrice(miniCartService.countCartPrice(cart));
сделай отдельный сервис для калькуляции прайса, мини карт то тут не при чём

2020-06-09 13:42 UTC, AndreikaInactive commented on core/src/main/java/com/es/core/cart/HttpSessionCartService.java
> +        if (!quantityValidator.isValid(phoneId, quantity)) {
так делай все сразу  в методе - поиск энтри
параметры как дубликаты выглядят

2020-06-09 13:42 UTC, AndreikaInactive commented on core/src/main/java/com/es/core/config/ApplicationPropertySourcePlaceholderConfigurer.java
> +public class ApplicationPropertySourcePlaceholderConfigurer extends PropertySourcesPlaceholderConfigurer
как и брату - думаю он не нужен

2020-06-09 13:42 UTC, AndreikaInactive commented on core/src/main/java/com/es/core/model/phone/JdbcPhoneDao.java
> +    @Autowired
и это, инжекти через xml или @value

2020-06-09 13:42 UTC, AndreikaInactive commented on core/src/main/java/com/es/core/model/phone/JdbcPhoneDao.java
> +        if ((offset < 0) || (limit < 0) || (searchQuery == null) || (sortField == null) || (sortOrder == null)
мб в сервисе проаасертай, например Assert.notNull

2020-06-09 13:42 UTC, AndreikaInactive commented on core/src/main/java/com/es/core/model/phone/JdbcPhoneDaoException.java
> +public class JdbcPhoneDaoException extends RuntimeException {
мб спринговского будет достаточно

2020-06-09 13:42 UTC, AndreikaInactive commented on core/src/main/java/com/es/core/services/DefaultMiniCartService.java
> +            cartService.addPhone(cartItem.getPhoneId(), cartItem.getQuantity());
думаю это всё не нужно - миникарта просто создаётся из обычной, простой маппинг

2020-06-09 13:42 UTC, AndreikaInactive commented on core/src/main/java/com/es/core/services/JdbcPhoneService.java
> +        String query = "";
тоже не понял, зачем нужен весь парсинг

2020-06-09 13:42 UTC, AndreikaInactive commented on core/src/main/resources/context/applicationContext-core.xml
> +    <bean class="com.es.core.config.ApplicationPropertySourcePlaceholderConfigurer">
и это зачем

2020-06-09 13:42 UTC, AndreikaInactive commented on core/src/main/resources/context/applicationContext-core.xml
> +    <bean id = "miniCart" class="com.es.core.cart.MiniCart"></bean>
и это - тут мб обычного бина хватит, карточка же всегда в сессии

2020-06-09 13:42 UTC, AndreikaInactive commented on web/src/main/java/com/es/phoneshop/web/controller/AjaxCartController.java
> +        String message = "";
собирай и возвращай месседжи в эксепшен хэндлере

2020-06-09 13:42 UTC, AndreikaInactive commented on web/src/main/java/com/es/phoneshop/web/controller/pages/PageControllerAdvice.java
> +    public String handleJdbcPhoneDaoException() {
а для обычных exception будет редирект?

2020-06-09 13:42 UTC, AndreikaInactive commented on web/src/main/java/com/es/phoneshop/web/controller/pages/ProductListPageBean.java
> +public class ProductListPageBean {
можно проще - ProductPageData, спринг тут не нужен - это просто дто

2020-06-09 13:42 UTC, AndreikaInactive commented on web/src/main/java/com/es/phoneshop/web/controller/pages/ProductListPageController.java
> +        pageBean.setPhones(phoneService.getPhoneList(page, query, sortField, sortOrder));
просто бери page data и сетай в модель, там всё уже должно быть

2020-06-09 13:42 UTC, AndreikaInactive commented on web/src/main/webapp/WEB-INF/pages/productList.jsp
> +            <td>Brand <tags:sortLink field="brand" order="ASC"/> <tags:sortLink field="brand" order="DESC"/></td>
зачем хардкодить?

2020-06-09 13:55 UTC, ElPerro3228 commented on core/src/main/java/com/es/core/config/ApplicationPropertySourcePlaceholderConfigurer.java
> +public class ApplicationPropertySourcePlaceholderConfigurer extends PropertySourcesPlaceholderConfigurer
Я просто беру сортировки из проперти файла через environment и, пока я не добавил этот класс, мне всегда нуллы приходили вместо проперти.

2020-06-09 15:54 UTC, ElPerro3228 commented on core/src/main/java/com/es/core/model/phone/JdbcPhoneDao.java
> +        if ((offset < 0) || (limit < 0) || (searchQuery == null) || (sortField == null) || (sortOrder == null)
типа отдельный какой-то сервис под эти проверки создать? Или в сервисе который вызывает это всё сделать

2020-06-09 17:58 UTC, ElPerro3228 commented on core/src/main/java/com/es/core/services/JdbcPhoneService.java
> +        String query = "";
это для того чтобы создать поиск в бд по каждому слову, которые были введены в поисковую строку + Влад сказал, что это должно быть безопасно для sql-инъекций поэтому я делал это через NameParameterdJdbcTemplate. Там ещё метод ниже есть, где я создаю SqlParameterSource.

2020-06-10 07:55 UTC, AndreikaInactive requested changes

2020-06-10 07:55 UTC, AndreikaInactive commented on core/src/main/java/com/es/core/cart/HttpSessionCartService.java
> +        cart.setCartPrice(cartPriceCalculationService.calculateCartPrice(cart));
calculate в общем случае лучше делать отдельно - при добавлении 10 айтемов у тебя сейчас 10 калькулейтов

2020-06-10 07:55 UTC, AndreikaInactive commented on core/src/main/java/com/es/core/model/phone/JdbcPhoneDao.java
> +        return properties.getProperty("sortField." + sortField);
так инжекти сразу листом, спринг сам сконвертит
обычно нет нужды пользоваться environment/properties напрямую

2020-06-10 07:55 UTC, AndreikaInactive commented on core/src/main/java/com/es/core/model/phone/JdbcPhoneDao.java
> +        String[] words = query.split(" ");
я ж вроде просил - приведите пример зачем это делается

2020-06-10 07:55 UTC, AndreikaInactive commented on core/src/main/java/com/es/core/services/DefaultCartPriceCalculationService.java
> +        double price = cartItems.stream()
сразу делай расчёты в bd, с даблом возможны промежуточные погрешности
вообще с деньгами всегда делать как минимум через bd

2020-06-10 07:55 UTC, AndreikaInactive commented on core/src/main/java/com/es/core/services/DefaultProductPageDataService.java
> +            if (propertyName.startsWith("sortField.")) {
либо сделай проперти со списком стрингов через запятую, либо как то через префикс попробовать, но это мб только в boot 
кастомный код не нужен

2020-06-10 08:07 UTC, ElPerro3228 commented on core/src/main/java/com/es/core/model/phone/JdbcPhoneDao.java
> +        String[] words = query.split(" ");
ну вот в строке поиска я введу Apple IPhone 6, метод засплитит эту строку и в бренде и в модели по каждому слову посмотрит, есть ли соответствующий продукт

2020-06-10 14:32 UTC, ElPerro3228 commented on core/src/main/java/com/es/core/services/DefaultCartPriceCalculationService.java
> +        double price = cartItems.stream()
Там же просто при подсчёте нужно учитывать количество телефонов в карте, а я не знаю как в бд передать количество какого либо конкретного телефона, и потом ещё произвести рассчёт учитывая его количество.

2020-06-10 20:08 UTC, AndreikaInactive commented on core/src/main/java/com/es/core/model/phone/JdbcPhoneDao.java
> +        String[] words = query.split(" ");
думаю для сэмпл проекта можно сделать проще - like сёрч инпута с вайлдкардами по обоим полям в базе

2020-06-10 20:28 UTC, AndreikaInactive requested changes

2020-06-10 20:28 UTC, AndreikaInactive commented on core/src/main/java/com/es/core/cart/HttpSessionCartService.java
> +        cart.setCartPrice(cartPriceCalculationService.calculateCartPrice(cart));
а когда появится деливери прайс? сетай все прайсы сразу в прайс сервисе, так и проще использовать, и вся логика в одном месте

2020-06-10 20:28 UTC, AndreikaInactive commented on core/src/main/java/com/es/core/services/DefaultCartPriceCalculationService.java
> +        BigDecimal cartPrice = new BigDecimal("0");
ок, но попробуй все сделать через стримы - хороший пример попрбовать

2020-06-11 20:29 UTC, AndreikaInactive requested changes

2020-06-11 20:29 UTC, AndreikaInactive commented on core/src/main/java/com/es/core/model/phone/JdbcPhoneDao.java
> +        String query = "brand like :query or model like :query";
константа

2020-06-11 20:29 UTC, AndreikaInactive commented on core/src/main/java/com/es/core/services/DefaultCartPriceCalculationService.java
> +    private String deliveryPrice;
пользуйся конвершеном спринга и избегай стрингов там где нужен другой тип - сразу инжекть бд

2020-06-14 15:04 UTC, merged