Task 3
ElPerro3228/phoneshop pull request #3
Opened 2020-06-19 16:14 UTC by ElPerro3228

2020-06-22 07:39 UTC, AndreikaInactive requested changes

2020-06-22 07:39 UTC, AndreikaInactive commented on core/src/main/java/com/es/core/services/JdbcPhoneService.java
> +        if (phone.isPresent()) {
orElseThrow вместо if, старайся пользоваться опшионалом без isPresent/get

2020-06-22 07:39 UTC, AndreikaInactive commented on core/src/main/java/com/es/core/services/DefaultCartPageDataService.java
> +        for (CartItem cartItem : cartItems) {
это для ui? а порядок важен? чем обычный карт не подходит?

2020-06-22 07:39 UTC, AndreikaInactive commented on web/src/main/java/com/es/phoneshop/web/controller/filters/GetMethodConvertingFilter.java
> +            public String getMethod() {
хм, а зачем форсить гет?) не думаю что это нужно

2020-06-22 07:39 UTC, AndreikaInactive commented on web/src/main/java/com/es/phoneshop/web/controller/pages/CartPageController.java
> +        if (!errors.hasErrors()) {
а почему нельзя апдейтнуть айтем в ноль? в валидаторе чек

2020-06-22 07:39 UTC, AndreikaInactive commented on web/src/main/java/com/es/phoneshop/web/controller/pages/CartPageController.java
>      @RequestMapping(method = RequestMethod.PUT)
почему пут для форм реквеста? вообще можно, но понадобится hidden method filter или че то такое, который это конвертит в спринге

2020-06-22 07:39 UTC, AndreikaInactive commented on web/src/main/java/com/es/phoneshop/web/controller/pages/CartPageController.java
> +        BigDecimal cartPrice = cartPriceCalculationService.calculateCartPrice(cart);
прайс уже должен быть посчитан, контроллер знать такие детали, а просто отдавать дату

2020-06-22 07:39 UTC, AndreikaInactive commented on web/src/main/java/com/es/phoneshop/web/controller/pages/ProductDetailsPageController.java
> +        MiniCart miniCart = miniCartService.createMiniCart(cart);
можно сделать в сервисе метод - getCurrentMiniCart, раз много где нужен
а чтобы добавлять в модель - например интерсептор спринговый, для интереса

2020-06-22 07:39 UTC, AndreikaInactive commented on web/src/main/webapp/WEB-INF/web.xml
> +    <filter-name>getMethodConvertingFilter</filter-name>
а, вот они
зачем тогда кастомный?

2020-06-22 07:58 UTC, ElPerro3228 commented on web/src/main/java/com/es/phoneshop/web/controller/filters/GetMethodConvertingFilter.java
> +            public String getMethod() {
проблема в том, что на контролер идёт пут запрос и он потом на jsp форсится, а jsp не принимает пут запрос, ну и ошибка падает

2020-06-22 07:59 UTC, ElPerro3228 commented on web/src/main/java/com/es/phoneshop/web/controller/pages/CartPageController.java
>      @RequestMapping(method = RequestMethod.PUT)
там в документе по заданию было: сделать пут не используя аякс. Я в начале сделал всё в аякс контроллере, а потом увидел, что задание немного другое

2020-06-22 10:07 UTC, ElPerro3228 commented on core/src/main/java/com/es/core/services/DefaultCartPageDataService.java
> +        for (CartItem cartItem : cartItems) {
это да для ui, просто из мапы удобнее было связать инпут формы с значениями + метод update из карт сервиса принимает мапу, поэтому подумал лучше сразу мапу использовать

2020-06-22 10:13 UTC, ElPerro3228 commented on web/src/main/java/com/es/phoneshop/web/controller/pages/CartPageController.java
> +        if (!errors.hasErrors()) {
получается удалять айтем из карты, если 0 встретился?

2020-06-23 08:21 UTC, AndreikaInactive requested changes

2020-06-23 08:21 UTC, AndreikaInactive commented on core/src/main/java/com/es/core/services/DefaultCartPageDataService.java
> +        for (CartItem cartItem : cartItems) {
ну ок, как по мне - лучше просто отдавать карту в универсальном формате, и уже на фронте делать что угодно
можно перемаппить карту в подроббное дто, если в её структуре что то не устраивает

2020-06-26 13:16 UTC, merged