Task 4
ElPerro3228/phoneshop pull request #4
Opened 2020-07-02 19:42 UTC by ElPerro3228

2020-07-07 21:29 UTC, AndreikaInactive requested changes

2020-07-07 21:29 UTC, AndreikaInactive commented on core/src/main/java/com/es/core/converters/OrderIdToOrderItemsConverter.java
> +        Long orderId = Long.parseLong(id);
по мне так лишнее, зачем конвертер?

2020-07-07 21:29 UTC, AndreikaInactive commented on core/src/main/java/com/es/core/model/order/Order.java
> +                 String contactPhoneNo, OrderStatus status) {
огромные конструкторы - плохо, или один или уже через шаблон builder

2020-07-07 21:29 UTC, AndreikaInactive commented on core/src/main/java/com/es/core/model/order/OrderStatus.java
> +    private Long id;
непонятное айди - зачем в енаме?

2020-07-07 21:29 UTC, AndreikaInactive commented on core/src/main/java/com/es/core/model/phone/JdbcStockDao.java
> +        stock.setPhone(phoneService.getPhone(phoneId));
сервис в дао

2020-07-07 21:29 UTC, AndreikaInactive commented on core/src/main/java/com/es/core/order/JdbcOrderDao.java
> +    public Optional<List<OrderItem>> getOrderItemsByOrderId(Long id) {
лист не надо врапать- он просто пустой если ничего нет

2020-07-07 21:29 UTC, AndreikaInactive commented on core/src/main/java/com/es/core/order/JdbcOrderDao.java
> +            orderItems.forEach(orderItem -> orderItem.setOrder(order));
сделай тогда уже метод на ордере, который обе стороны апдейдает в памяти

2020-07-07 21:29 UTC, AndreikaInactive commented on core/src/main/java/com/es/core/order/OrderRowMapper.java
> +        statusMap.put(1L, OrderStatus.NEW);
ну, я бы тогда держал строкой в базе и добавил метод fromString в енам, было бы понятней

2020-07-07 21:29 UTC, AndreikaInactive commented on core/src/main/java/com/es/core/order/OrderServiceImpl.java
> +        order.setStatus(OrderStatus.NEW);
а почему в конверте не сетать?

2020-07-07 21:29 UTC, AndreikaInactive commented on core/src/main/java/com/es/core/order/OrderServiceImpl.java
> +        order.setSubtotal(cartPriceCalculationService.calculateSubtotalPrice(cart));
мб посчитать карту, а поотм просто копировать на ордер

2020-07-07 21:29 UTC, AndreikaInactive commented on core/src/main/java/com/es/core/order/OrderServiceImpl.java
> +    private Order convertCartToOrder(Cart cart) {
вот конвертацию почему не вынеси в конвертер

2020-07-07 21:29 UTC, AndreikaInactive commented on core/src/main/java/com/es/core/order/OrderServiceImpl.java
>      @Override
а транзакция есть?

2020-07-07 21:29 UTC, AndreikaInactive commented on core/src/main/java/com/es/core/order/OrderServiceImpl.java
> +        orderDao.saveOrder(order);
не совсем понял зачем сохранять при создании отдельно от плейса?

2020-07-07 21:29 UTC, AndreikaInactive commented on core/src/main/java/com/es/core/services/DefaultStockService.java
> +        stock.setStock(stock.getStock() - deductionNumber);
ну ок, но вообще можно сразу кверёй апдейтнуть ) обычно стоки - достаточно concurrent штука

2020-07-07 21:29 UTC, AndreikaInactive commented on pom.xml
> +        <groupId>com.googlecode.libphonenumber</groupId>
опять пошли дублироваться депенденси? надо разобраться с модулями

2020-07-07 21:29 UTC, AndreikaInactive commented on web/src/main/java/com/es/phoneshop/web/controller/pages/OrderPageController.java
> +        Order order = orderService.createOrder(cart);
так он что, каждый раз новый создается по гету?

2020-07-07 21:29 UTC, AndreikaInactive commented on web/src/main/java/com/es/phoneshop/web/controller/pages/OrderPageController.java
> +        orderItemsValidator.validate(order, errors);
сток мб тут же проверять

2020-07-08 11:57 UTC, ElPerro3228 commented on core/src/main/java/com/es/core/model/phone/JdbcStockDao.java
> +        stock.setPhone(phoneService.getPhone(phoneId));
а так получается нельзя делать делать? там же просто в сток должен телефон засетаться

2020-07-08 12:35 UTC, ElPerro3228 commented on core/src/main/java/com/es/core/order/JdbcOrderDao.java
> +            orderItems.forEach(orderItem -> orderItem.setOrder(order));
в методе ордера setOrderItems просетать всем итемам ордер, я правильно понимаю?

2020-07-08 12:49 UTC, ElPerro3228 commented on core/src/main/java/com/es/core/order/OrderServiceImpl.java
>      @Override
ну у меня все дао классы с аннотацией Transactional, так что, наверное, транзакция есть

2020-07-08 12:56 UTC, ElPerro3228 commented on core/src/main/java/com/es/core/order/OrderServiceImpl.java
> +        order.setSubtotal(cartPriceCalculationService.calculateSubtotalPrice(cart));
ну кстати в карте только totalPrice, а вот 2 остальных придётся брать через сервис

2020-07-08 13:07 UTC, ElPerro3228 commented on web/src/main/java/com/es/phoneshop/web/controller/pages/OrderPageController.java
> +        orderItemsValidator.validate(order, errors);
я уже проверяю, я этот валидатор для этого и создавал

2020-07-08 13:27 UTC, ElPerro3228 commented on pom.xml
> +        <groupId>com.googlecode.libphonenumber</groupId>
ну я вижу только одно объявление, не считая того что указано в дочернем пом файле

2020-07-08 13:44 UTC, AndreikaInactive commented on core/src/main/java/com/es/core/model/phone/JdbcStockDao.java
> +        stock.setPhone(phoneService.getPhone(phoneId));
вынеси хотя бы в маппер сервис, хотя по идее это через фон дао можно закверить
да, пока старайся не смешивать - дао ниже уровнем, чем сервис

2020-07-08 13:45 UTC, AndreikaInactive commented on pom.xml
> +        <groupId>com.googlecode.libphonenumber</groupId>
у тебя один в core/pom и еще здесь, зачем?
в коре и вебе все депенденси на либы

2020-07-08 13:45 UTC, AndreikaInactive commented on web/src/main/java/com/es/phoneshop/web/controller/pages/OrderPageController.java
> +        orderItemsValidator.validate(order, errors);
видел при плейсе еще раз чекается qty

2020-07-08 14:17 UTC, ElPerro3228 commented on core/src/main/java/com/es/core/order/OrderServiceImpl.java
> +        orderDao.saveOrder(order);
просто мне нужно было, как-то сохранить информацию у промежуточного заказа(который формируется при переходе со страницы корзины на страницу заказа и пока не имеет контактной информации). Я вообще могу это в сессии сохранить, ну или есть какой-то другой способ, который я не знаю.

2020-07-08 16:54 UTC, ElPerro3228 commented on web/src/main/java/com/es/phoneshop/web/controller/pages/OrderPageController.java
> +        orderItemsValidator.validate(order, errors);
а точно, ну тогда удалю из плейса проверку

2020-07-08 18:18 UTC, ElPerro3228 commented on core/src/main/java/com/es/core/converters/OrderIdToOrderItemsConverter.java
> +        Long orderId = Long.parseLong(id);
ну он мне тут понадобился для того, чтобы потом не вызывать сервис и не сетать их в контроллере, а сразу в контроллере получить полный ордер, со всеми полями, и просто вызвать плейс метод

2020-07-14 16:15 UTC, AndreikaInactive requested changes

2020-07-14 16:15 UTC, AndreikaInactive commented on core/src/main/java/com/es/core/converters/CartToOrderConverter.java
> +        order.setSubtotal(cartPriceCalculationService.calculateSubtotalPrice(cart));
просто пересчитай карту перед сабмитом и пересетай прайс в ордер

2020-07-14 16:15 UTC, AndreikaInactive commented on core/src/main/java/com/es/core/converters/CartItemsToOrderItemsConverter.java
> +        List<OrderItem> orderItems = new ArrayList<>();
более реюзабл - конвертер без листов и вызывать через стрим мап коллект из ордер конвертера

2020-07-14 16:15 UTC, AndreikaInactive commented on core/src/main/java/com/es/core/model/phone/JdbcStockDao.java
> +        stock.setPhone(phone.orElseThrow(PhoneNotFoundException::new));
вынеси в маппер

2020-07-14 16:15 UTC, AndreikaInactive commented on web/src/main/java/com/es/phoneshop/web/controller/pages/OrderPageController.java
> -        Order order = orderService.createOrder(cart);
как и брату - почему это все при гете? у вас же есть форма и карта, когда он самбитит форму - создаём ордер из карты и формы и сохраняем
или эти ре-сэйвы ордера и айтемов для чего то ещё нужны?

2020-07-14 16:15 UTC, AndreikaInactive commented on web/src/main/java/com/es/phoneshop/web/controller/pages/OrderPageController.java
> +        Order sessionOrder = (Order) session.getAttribute(ORDER_SESSION_NAME);
в любом случае - со спрингом вы не работаете с сессией в чистом виде, это слишком низкий уровень апи

2020-07-14 17:34 UTC, ElPerro3228 commented on web/src/main/java/com/es/phoneshop/web/controller/pages/OrderPageController.java
> -        Order order = orderService.createOrder(cart);
ну я это исправил, я просто на форму отправляю ордер, в котором просто находятся его айтемы

2020-07-14 17:52 UTC, ElPerro3228 commented on web/src/main/java/com/es/phoneshop/web/controller/pages/OrderPageController.java
> +        Order sessionOrder = (Order) session.getAttribute(ORDER_SESSION_NAME);
ну да я чувствовал, что что-то не так делаю, потому что httpSession я использовал, когда на сервлетах курс проходил, да и я с самого начала тут попытался возможностями спринга это сделать, в том плане, что просто над ордер аннотацию поставил, что это компонент с session scope, как это с картой было. Но потом сразу проблема появилась, когда я передавал такой ордер на форму там на джсп непонятная ошибка появлялась(мол он не может поля взять и единственная мысль, которая у меня была, почему так происходило - это то, что спринг создаёт прокси поверх этого объекта). Ну в общем, из-за того что я не осилил эту ошибку я решил сессию в чистом виде достать

2020-07-14 18:08 UTC, ElPerro3228 commented on web/src/main/java/com/es/phoneshop/web/controller/pages/OrderPageController.java
> -        Order order = orderService.createOrder(cart);
ой, а теперь, я заметил, что на странице нет прайсов, и всё равно я возвращаюсь к методу createOrder, потому что он прайсы считает и статус сетает, да и он же просто конвертирует карту в ордер

2020-07-14 18:32 UTC, ElPerro3228 commented on core/src/main/java/com/es/core/converters/CartToOrderConverter.java
> +        order.setSubtotal(cartPriceCalculationService.calculateSubtotalPrice(cart));
я так пересчитаю только subtotalprice, в карте же нет стоимости доставки и общей стоимости

2020-07-14 18:40 UTC, ElPerro3228 commented on core/src/main/java/com/es/core/converters/CartToOrderConverter.java
> +        order.setSubtotal(cartPriceCalculationService.calculateSubtotalPrice(cart));
их всё равно приходится из сервиса доставать

2020-07-15 09:05 UTC, ElPerro3228 commented on web/src/main/java/com/es/phoneshop/web/controller/pages/OrderPageController.java
> -        Order order = orderService.createOrder(cart);
я в общем оставил метод createOrder, потому что он по сути ничего кроме конвертирования карты в ордер и не делает, в базу данных, как раньше не сохраняет, в сессии он теперь не хранится, я это всё уже удалил. Просто создаётся объект ордер, который потом на джсп используется. Может название поменять, чтобы не выглядело будто заказ создаётся при гете и я что-то сохраняю, не знаю.

2020-07-16 14:04 UTC, AndreikaInactive requested changes

2020-07-16 14:04 UTC, AndreikaInactive commented on core/src/main/java/com/es/core/converters/CartToOrderConverter.java
> +        BigDecimal deliveryPrice = cartPriceCalculationService.getDeliveryPrice();
прайс кстати лучше держать на карте - мало ли там какой промоушен на него будет, а он фиксировано с сервиса берется

2020-07-16 14:04 UTC, AndreikaInactive commented on web/src/main/java/com/es/phoneshop/web/controller/pages/OrderPageController.java
> -        Order order = orderService.createOrder(cart);
так а зачем тебе ордер, пока он не создан? отдавай в модель карту, и с нее все прайсы бери
а ордер создавай только при посте формы

2020-07-16 14:31 UTC, ElPerro3228 commented on web/src/main/java/com/es/phoneshop/web/controller/pages/OrderPageController.java
> -        Order order = orderService.createOrder(cart);
а у меня всего этого уже нет. Я сейчас просто карту отдаю на модель

2020-07-16 14:33 UTC, ElPerro3228 commented on core/src/main/java/com/es/core/converters/CartToOrderConverter.java
> +        BigDecimal deliveryPrice = cartPriceCalculationService.getDeliveryPrice();
имеешь ввиду деливери прайс?

2020-07-20 13:22 UTC, AndreikaInactive requested changes

2020-07-20 13:22 UTC, AndreikaInactive commented on core/src/main/java/com/es/core/cart/HttpSessionCartService.java
> +        BigDecimal cartPrice = cartPriceCalculationService.calculateCartPrice(cart);
я же вроде както писал) сетай все прайсы на карту в прайс сервисе - как правило проще и производительнее делать это за один метод, чем дергать по несколько раз. Запрайсил карту - и юзай эти прайсы как хочешь

2020-07-20 20:06 UTC, ElPerro3228 commented on core/src/main/java/com/es/core/cart/HttpSessionCartService.java
> +        BigDecimal cartPrice = cartPriceCalculationService.calculateCartPrice(cart);
да я помню это, что-то из головы вылетело(

2020-07-21 11:35 UTC, AndreikaInactive approved these changes

2020-07-21 11:35 UTC, merged