Task 5
ElPerro3228/phoneshop pull request #5
Opened 2020-07-23 07:06 UTC by ElPerro3228

2020-07-23 08:48 UTC, AndreikaInactive requested changes

2020-07-23 08:48 UTC, AndreikaInactive commented on web/pom.xml
> +    <dependency>
я думал разобрались с помом?

2020-07-23 08:48 UTC, AndreikaInactive commented on web/pom.xml
> +      <groupId>org.assertj</groupId>
и это тут зачем

2020-07-23 08:48 UTC, AndreikaInactive commented on web/src/main/java/com/es/phoneshop/config/SpringSecurityConfiguration.java
> +public class SpringSecurityConfiguration extends WebSecurityConfigurerAdapter {
так тут через джаву или xml конфиг?

2020-07-23 08:48 UTC, AndreikaInactive commented on web/src/main/java/com/es/phoneshop/web/controller/pages/admin/LoginController.java
> +    public String login(@RequestParam(value = "error", required = false) String error,
по мелочи - юзайтие GetMapping, MessageSourceAccessor для месседжей

2020-07-23 08:48 UTC, AndreikaInactive commented on web/src/main/java/com/es/phoneshop/web/controller/pages/admin/OrdersPageController.java
> +        order.setStatus(orderStatus);
логика не должна быть в контроллере + попробуйте юзать пут с телом метода, можно через ajax

2020-07-23 08:48 UTC, AndreikaInactive commented on web/src/main/webapp/WEB-INF/spring-security.xml
> +				<user name="mkyong" password="$2a$10$eDIvDPiMYyoq4XOAo5dRoe7XhR7hPepsztYO7yORGAl0u.pBLp3hC" authorities="ROLE_USER" />
)

2020-07-23 08:48 UTC, AndreikaInactive commented on web/src/test/java/com/es/phoneshop/web/controller/pages/OrdersPageControllerTest.java
> +@ContextConfiguration(locations = {"classpath:applicationContext.xml", "classpath:spring-security.xml", "classpath:dispatcher-servlet.xml"})
вроде же делали integrationTest аннотацию? зачем отдельно сетапить контекст?

2020-07-23 08:48 UTC, AndreikaInactive commented on web/src/test/resources/spring-security.xml
> +	<http auto-config="true">
дубликат

2020-07-23 09:01 UTC, ElPerro3228 commented on web/src/main/java/com/es/phoneshop/config/SpringSecurityConfiguration.java
> +public class SpringSecurityConfiguration extends WebSecurityConfigurerAdapter {
а блин, забыл удалить

2020-07-23 09:43 UTC, ElPerro3228 commented on web/src/test/java/com/es/phoneshop/web/controller/pages/OrdersPageControllerTest.java
> +@ContextConfiguration(locations = {"classpath:applicationContext.xml", "classpath:spring-security.xml", "classpath:dispatcher-servlet.xml"})
а как тогда нормально сделать? Вроде аннотация IntegrationTest deprecated. И как можно сделать этот тест без отдельного сетапа контекста?

2020-07-23 14:15 UTC, AndreikaInactive commented on web/src/test/java/com/es/phoneshop/web/controller/pages/OrdersPageControllerTest.java
> +@ContextConfiguration(locations = {"classpath:applicationContext.xml", "classpath:spring-security.xml", "classpath:dispatcher-servlet.xml"})
в первых прах же делали, как это депрекейтед? кастомная
в ней должен подниматься весь контекст

2020-07-23 14:58 UTC, ElPerro3228 commented on web/src/test/java/com/es/phoneshop/web/controller/pages/OrdersPageControllerTest.java
> +@ContextConfiguration(locations = {"classpath:applicationContext.xml", "classpath:spring-security.xml", "classpath:dispatcher-servlet.xml"})
а, но мы не аннотацию делали, а класс абстрактный. я поэтому и запутался

2020-07-28 11:30 UTC, AndreikaInactive requested changes

2020-07-28 11:30 UTC, AndreikaInactive commented on web/src/main/java/com/es/phoneshop/web/controller/pages/admin/OrdersPageController.java
> +        return new ResponseEntity<>(map, HttpStatus.OK);
с точки зрения апи - достаточно знать об успешности ситуации, т.е вернуть ResponseEntity.ok()
остальное уже избыточные телодвижения

2020-07-28 11:30 UTC, AndreikaInactive commented on web/src/test/java/com/es/phoneshop/web/controller/IntegrationTest.java
> +@ContextConfiguration(locations = {"classpath:applicationContext.xml", "file:src/main/webapp/WEB-INF/spring-security.xml", "classpath:dispatcher-servlet.xml"})
странно что из файла берешь ) просто включи секьюрити в appContext

2020-07-28 11:30 UTC, AndreikaInactive commented on web/src/test/java/com/es/phoneshop/web/controller/IntegrationTest.java
> +@Documented
а почему теперь аннотация? абстрактный класс не подошел?

2020-07-28 14:59 UTC, ElPerro3228 commented on web/src/test/java/com/es/phoneshop/web/controller/IntegrationTest.java
> +@Documented
решил с аннотацией сделать. Можно было и с абстрактным классом. А в чём кстати разница: использовать то или другое? Просто в результате и там и там интеграционный тест.

2020-07-28 19:59 UTC, AndreikaInactive commented on web/src/test/java/com/es/phoneshop/web/controller/IntegrationTest.java
> +@Documented
если получилось и так и так, то ок, я думал абстрактный уже в проекте есть

2020-07-28 20:00 UTC, merged